HomeworkPublish/urls.py
from django.urls import path
from . import views

app_name = 'HomeworkPublish'

urlpatterns = [
    path('Homework_list/', views.Homework_list, name='Homework_list'),
    path('Homework_Publish/<int:id>',views.Homework_Publish,name='Homework_Publish'),
    path('Homework_delete/<int:id>/',views.Homework_delete,name='Homework_delete'),
]

Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('', views.主页, name = '主页'),
    path('login/', views.登录, name = '登录'),
    path('logout/', views.登出, name = '登出'),
    path('register/', views.注册, name = '注册'),
    path('addcourse/', views.addcourse, name = 'addcourse'),
    path('joincourse/', views.joincourse, name = 'joincourse'),
    path('coursedetail/<int:id>',views.coursedetail, name = 'coursedetail'),
    path('coursedelete/<int:id>',views.coursedelete, name = 'coursedelete'),
    path('addassistant/<int:id>',views.addassistant, name = 'addassistant'),
    path('upload/<int:id>/',views.upload,name = 'upload'),
     path('user-center/', views.个人中心, name = '个人中心'),
    path('user-center/edit-profile', views.编辑个人信息, name = '编辑个人信息'),
    path('user-center/change-password', views.修改密码, name = '修改密码'),
]

projectTen/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
import projectTen.settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls')),
    path('',include('HomeworkPublish.urls',namespace='HomeworkPublish')),
    path('captcha/', include('captcha.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    
]+ static (projectTen.settings.MEDIA_URL, document_root=projectTen.settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = "upload"

urlpatterns=[
    path('',views.register),
    path('filelist/',views.display,name="filelist"),
]

Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class 普通会员表(models.Model):
    用户 = models.OneToOneField(User, on_delete=models.CASCADE)
    昵称 = models.CharField(blank=True,max_length=50)
    身份 = models.CharField(max_length=2)
    
    class Meta:
        verbose_name_plural = "普通会员表"
    
class course(models.Model):
    teacherName = models.CharField(max_length=10)
    courseNum = models.CharField(max_length=10)
    courseName = models.CharField(max_length=10)
class stucourse(models.Model):
    studentName = models.CharField(max_length=10)
    thecourse = models.ForeignKey('course',on_delete=models.CASCADE)

class asscourse(models.Model):
    assistantName = models.CharField(max_length=10)
    thecourse = models.ForeignKey('course',on_delete=models.CASCADE)

upload/models.py
from django.db import models

# Create your models here.

# Create your models here.
class userfile(models.Model):
    username = models.CharField(max_length = 30)
    courseNum = models.CharField(max_length = 10,null=True)
    headImg = models.FileField(upload_to= './files/')
    #所以是用upload_to来指定文件存放的前缀路径
    def __str__(self):
        return self.courseNum

Login/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from captcha.fields import CaptchaField

class 自定义登录表单(AuthenticationForm):
    验证码 = CaptchaField()

class 自定义编辑表单(UserChangeForm):
    昵称 = forms.CharField(required=False,max_length=50)
    身份 = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username','password','email','昵称','身份')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique':'该用户名已存在！' , 'invalid':'该用户名格式不符合要求！'}


class 自定义注册表单(UserCreationForm):
    昵称 = forms.CharField(required=False,max_length=50)
    身份 = forms.CharField(max_length=100)
    验证码 = CaptchaField()

    class Meta:
        model = User
        fields = ('username','password1','password2','email','昵称','身份')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'unique':'该用户名已存在！' , 'invalid':'该用户名格式不符合要求！'}

Login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm,UserChangeForm, PasswordChangeForm
from django.http import HttpResponse
from django.db.models import Q
from .forms import 自定义注册表单,自定义编辑表单,自定义登录表单
from .models import 普通会员表
from django.contrib.auth.decorators import login_required
from HomeworkPublish.models import Homework
from upload.models import userfile
from .models import course
from .models import stucourse
from .models import asscourse
# Create your views here.

def 主页(request):
    if request.user.is_authenticated:
        mycourse=course.objects.filter(teacherName = request.user.username)
        sc = stucourse.objects.filter(studentName = request.user.username)
        ac = asscourse.objects.filter(assistantName = request.user.username)
        hw=Homework.objects.all()
        uf=userfile.objects.all()
        us=普通会员表.objects.all()
        nowu=普通会员表.objects.get(昵称 = request.user.username)
        request.session['role']=nowu.身份
        context={'hw':hw,'uf':uf,'us':us,'mycourse':mycourse,'sc':sc,'ac':ac}
        return render(request, 'Login/home.html',context)
    else:
        return render(request,'Login/home.html')



def 登录(require):
    if require.method == 'POST':
        登录表单 = 自定义登录表单(data= require.POST)
        if 登录表单.is_valid():

            用户 = authenticate(require,username=登录表单.cleaned_data['username'] ,password=登录表单.cleaned_data['password'] )

            login(require,用户)
            return redirect('Login:主页')
    else:
        登录表单 = 自定义登录表单()

    内容 = {'登录表单':登录表单, '用户':require.user}
    return render(require, 'Login/login.html',内容)


def 登出(request):
    try:
        del request.session['role']
    except KeyError:
        pass
    logout(request)
    return redirect('Login:主页')


def 注册(require):
    if require.method == 'POST':
        注册表单 = 自定义注册表单(require.POST)
        if 注册表单.is_valid():
            注册表单.save()
            用户 = authenticate(username=注册表单.cleaned_data['username'] ,password=注册表单.cleaned_data['password1'] )
            用户.email = 注册表单.cleaned_data['email']
            普通会员表(用户=用户,昵称=注册表单.cleaned_data['昵称'],身份=注册表单.cleaned_data['身份']).save()
            login(require,用户)
            return redirect('Login:主页')
    else:
        注册表单 = 自定义注册表单()

    内容 = {'注册表单':注册表单}
    return render(require, 'Login/register.html', 内容)
@login_required(login_url='Login:登录')
def 个人中心(require):
    内容 = {'用户': require.user}
    return render(require, 'Login/user-center.html', 内容)

@login_required(login_url='Login:登录')
def 编辑个人信息(require):
    if require.method == 'POST':
        编辑表单 = 自定义编辑表单(require.POST,instance = require.user)
        if 编辑表单.is_valid():
            编辑表单.save()
            require.user.普通会员表.昵称 = 编辑表单.cleaned_data['昵称']
            require.user.普通会员表.身份 = 编辑表单.cleaned_data['身份']
            require.user.普通会员表.save()
            return redirect('Login:个人中心')
    else:
        编辑表单 = 自定义编辑表单(instance = require.user)

    内容 = {'编辑表单':编辑表单, '用户':require.user}
    return render(require, 'Login/edit-profile.html', 内容)



@login_required(login_url='Login:登录')
def 修改密码(require):
    if require.method == 'POST':
        改密表单 = PasswordChangeForm(data= require.POST,user = require.user)
        if 改密表单.is_valid():
            改密表单.save()
            return redirect('Login:登录')
    else:
        改密表单 = PasswordChangeForm(user = require.user)

    内容 = {'改密表单':改密表单, '用户':require.user}
    return render(require, 'Login/change-password.html', 内容)


def upload(request,id):
    uf=userfile()
    if request.method == "POST":
        uf.username = request.user.username
        uf.courseNum = id
        uf.headImg = request.FILES.get('tttt',None)
        uf.save()
        return HttpResponse('upload ok!')
    return render(request,'Login/upload.html',{'uf':uf})

def addcourse(request):
    Nowcourse = course()
    if request.method == "POST":
        Nowcourse.teacherName = request.user.username
        Nowcourse.courseNum = request.POST['courseNum']
        Nowcourse.courseName = request.POST['courseName']
        Nowcourse.save()
        return HttpResponse('添加成功')
    return render(request,'Login/addcourse.html',{'Nowcourse':Nowcourse})

def joincourse(request):
    search = request.GET.get('search')
    if search:
        target = course.objects.filter(
            Q(courseNum__icontains=search)
        )
    else:
        search=''
        target =  course.objects.all()
    join = request.GET.get('join')
    if join:
        joinCourse = stucourse()
        joinCourse.studentName = request.user.username
        joinCourse.thecourse = target[0]
        joinCourse.save()
    context = {'search':search,'target':target}
    return render(request,"Login/joincourse.html",context)


def coursedetail(request,id):
    mycourse=course.objects.get(id = id)
    sc = stucourse.objects.filter( thecourse_id = id)
    hw=Homework.objects.filter(courseNum = id)
    context = {'mycourse':mycourse,'sc':sc,'hw':hw}
    return render(request,'Login/coursedetail.html',context)

def coursedelete(request,id):
    target = course.objects.get(id=id)
    target.delete()
    return HttpResponse("已删除课程")

def addassistant(request,id):
    assistant = asscourse()
    Course = course.objects.get(id=id)
    if request.method == "POST":
        assistant.assistantName = request.POST['assistantName']
        assistant.thecourse = Course
        assistant.save()
        return HttpResponse('添加成功')
    return render(request,'Login/addassistant.html',{'Course':Course})

upload/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponse
from .models import userfile

def register(request):
    uf=userfile()
    if request.method == "POST":
        uf.username = request.POST['name']
        uf.username = request.POSt['courseNum']
        uf.headImg = request.FILES.get('tttt',None)

        uf.save()
        return HttpResponse('upload ok!')
    return render(request,'upload/register.html',{'uf':uf})

def display(request):
    filelist = userfile.objects.all()
    context = {'filelist':filelist}
    return render(request,"upload/filelist.html",context)

Login/templates/Login/addassistant.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>添加助教</title>
</head>
<body>
    <h1>主页</h1>
    {% if user.is_authenticated %}
        <a href = "{% url 'Login:登出' %}">登出</a>
        <p>当前用户:{{ user.username }}</p>
        <p>当前用户身份:{{ request.session.role }}</p>
        <p>当前课程：</p>
        <p>您为此课程添加助教</p>
        <form action="" method="post" >
            {% csrf_token %}
            <p>助教名称:<input type="text" name="assistantName" ></p>
            <input type="submit" value="ok">
        </form>
    {% else %}
        <a href = "{% url 'Login:登录' %}">登录</a>
        <a href = "{% url 'Login:注册' %}">注册</a>
    {% endif %}
</body>
</html>

Login/templates/Login/addcourse.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>添加课程</title>
</head>
<body>
    <h1>主页</h1>
    {% if user.is_authenticated %}
        <a href = "{% url 'Login:登出' %}">登出</a>
        <p>当前用户:{{ user.username }}</p>
        <p>当前用户身份:{{ request.session.role }}</p>
        <p>您正在添加课程</p>
        <form action="" method="post" >
            {% csrf_token %}
            <p>课程编号:<input type="text" name="courseNum" ></p>
            <p>课程名称:<input type="text" name="courseName" ></p>
            <input type="submit" value="ok">
        </form>
    {% else %}
        <a href = "{% url 'Login:登录' %}">登录</a>
        <a href = "{% url 'Login:注册' %}">注册</a>
    {% endif %}
</body>
</html>

Login/templates/Login/change-password.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>个人中心</h1>

    <a href = "{% url 'Login:主页' %}">回到主页</a>
    <a href = "{% url 'Login:个人中心' %}">个人中心</a>
    <a href = "{% url 'Login:编辑个人信息' %}">编辑个人信息</a>
    <a href = "{% url 'Login:修改密码' %}">修改密码</a>
    <a href = "{% url 'Login:登出' %}">登出</a>
        {{ 改密表单.errors }}
    <form action="" method = "POST">
        {% csrf_token %}
        {{ 改密表单.as_p }}
        
        <button type = "submit">提交</button>
    </form>
</body>
</html>

Login/templates/Login/coursedetail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>课程详情</title>
</head>
<body>
    <h1>课程详情页</h1>
    {% if user.is_authenticated %}
        <a href = "{% url 'Login:登出' %}">登出</a>
        <p>当前用户:{{ user.username }}</p>
        <p>当前用户身份:{{ request.session.role }}</p>
        <p>课程名称：{{mycourse.courseName}}</p>
        <p>授课教师：{{mycourse.teacherName}}</p>
        <p>参与课程学生：</p>
        {% for s in sc %}
            <p>{{s.studentName}}</p>
        {% endfor %}
        <p>作业列表：</p>
        {% for Homework in hw %}
            <p>
            作业内容：{{ Homework.Homework_text}}   发布时间：{{ Homework.Pub_time }} 截止时间：{{ Homework.deadline_date}} {{ Homework.deadline_time}}
            {% if request.session.role == '学生' %}
            <a href ="{% url 'Login:upload' Homework.id %}">提交此作业</a>
            {% endif %}
            {% if request.session.role == '教师' %}
            <a href ="{% url 'HomeworkPublish:Homework_delete' Homework.id %}">删除此作业</a>
            {% endif %}
            </p>
        {% endfor %}

        {% if request.session.role == '教师' %}
            <a href="{% url 'HomeworkPublish:Homework_Publish' mycourse.id  %}">发布作业</a>
            <a href="{% url 'Login:addassistant' mycourse.id  %}">为此课程添加助教</a>            
        {% endif %}


        
    {% else %}
        <a href = "{% url 'Login:登录' %}">登录</a>
        <a href = "{% url 'Login:注册' %}">注册</a>
    {% endif %}
</body>
</html>

Login/templates/Login/edit-profile.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>个人中心</h1>

    <a href = "{% url 'Login:主页' %}">回到主页</a>
    <a href = "{% url 'Login:个人中心' %}">个人中心</a>
    <a href = "{% url 'Login:编辑个人信息' %}">编辑个人信息</a>
    <a href = "{% url 'Login:修改密码' %}">修改密码</a>
    <a href = "{% url 'Login:登出' %}">登出</a>
        {{ 编辑表单.errors }}
    <form action="" method = "POST">
        {% csrf_token %}
        
        <p>
            <label for="id_username">用户名：</label>
            <input type="text" name="username" value="{{用户.username}}" maxlength="150" required id="id_username" />
            <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>
        </p>
        <p>
            <label for="id_email">电子邮件地址:</label>
            <input type="email" name="email" value="{{用户.email}}" maxlength="254" id="id_email">
        </p>
        <p>
            <label for="id_昵称">昵称:</label> 
            <input type="text" name="昵称" maxlength="50" id="id_昵称" value="{{用户.普通会员表.昵称}}" />
        </p>
        <p>
            <label for="id_身份">身份:</label> 
		    <input type = "radio" name = "身份" value = "学生">学生
            <input type = "radio" name = "身份" value = "助教">助教
            
		    <input type = "radio" name = "身份" value = "老师">老师
        </p>
        <button type = "submit">提交</button>
    </form>
</body>
</html>

Login/templates/Login/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>




<body background="/static/images/bg.jpg" style=" background-repeat:no-repeat ;background-size:100% 100%;
background-attachment: fixed;">

    <h1 class="text-center" style="color:blue">Good Homework Online</h1>
    {% if user.is_authenticated %}
        <a href = "{% url 'Login:登出' %}">登出</a>
        <a href = "{% url 'Login:个人中心' %}">个人中心</a>
        <p>当前用户:{{ user.username }}</p>
        <p>当前用户身份:{{ request.session.role }}</p>
        {% if request.session.role == '教师' %}
            <p><a href ="{% url 'Login:addcourse' %}">添加课程</a></p>
            <p>我的课程:</p>
            <ul>
            {% for course in mycourse %}
                <li><a  href ="{% url 'Login:coursedetail' course.id %}">{{ course.courseName }}</a>  <a  href ="{% url 'Login:coursedelete' course.id %}">删除此课程</a></li>

            {% endfor %}
            </ul>
        {% endif %}
        {% if request.session.role == '学生' %}
            <p><a  href ="{% url 'Login:joincourse' %}">加入课程</a></p>
            <p>我的课程:</p>
            <ul>
                {% for c in sc %}
                <li><a  href ="{% url 'Login:coursedetail' c.thecourse.id %}">{{ c.thecourse.courseName }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if request.session.role == '助教' %}
            <p>我管理的课程:</p>
            <ul>
                {% for c in ac %}
                <li><a  href ="{% url 'Login:coursedetail' c.thecourse.id %}">{{ c.thecourse.courseName }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        
    {% else %}
    <div style="text-align:center;">
        
        <a href = "{% url 'Login:登录' %}"  role="button" class="btn btn-outline-primary btn-lg img-circle " class="img-circle" >登录</a>
        <a href = "{% url 'Login:注册' %}"  role="button" class="btn btn-outline-primary btn-lg" class="img-circle" >注册</a>
    </div>
    {% endif %}
    


</body>
</html>

Login/templates/Login/joincourse.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>加入课程</title>
</head>
<body>
    <h1>主页</h1>
    {% if user.is_authenticated %}
        <a href = "{% url 'Login:登出' %}">登出</a>
        <p>当前用户:{{ user.username }}</p>
        <p>当前用户身份:{{ request.session.role }}</p>
        <p>您正在加入课程</p>
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline" >
                    <input type="text" 
                        class="form-control mb-2 mr-sm-2" 
                        name="search" 
                        placeholder="搜索..." 
                        required
                    >
                </form>
        </div>
        {% if search %}
        {% if target %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <ul>
                {% for targetfile in target %}    
                    <li>{{targetfile.id}}  {{targetfile.courseNum }}  {{ targetfile.teacherName }} 
                        <div class="row">
                            <div class="col-auto mr-auto">
                                <form class="form-inline" >
                                    <input type="submit" 
                                        name="join"
                                        value = "加入"  
                                        required
                                    >
                                </form>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <hr>        
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文件。</h4>
            <hr>
        {% endif %}
    {% endif %}
    {% else %}
        <a href = "{% url 'Login:登录' %}">登录</a>
        <a href = "{% url 'Login:注册' %}">注册</a>
    {% endif %}
</body>
</html>

Login/templates/Login/login.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>登录</h1>
    <a href = " {% url 'Login:主页' %} ">返回</a>
    <form action = "" method = "POST">
    	{% csrf_token %}
    	{{ 错误 }}
		
		<!---
    	<input type = "text" name = "username" placeholder = "用户名">
    	<input type = "password" name = "password" placeholder = "密码">
		-->
		
		<p>
		 <label for = "username">账号：</label>
		  <input type = "text" name = "username" placeholder = "用户名">
		 <br>
		 <label for ="password">密码：</label>
		  <input type = "password" name = "password" placeholder = "密码">
		 
		 <!--
		  <br>
		 <label for = "identity">身份:</label>
		  <input type = "radio" name = "身份" value = "学生">学生
		  <input type = "radio" name = "身份" value = "助教">助教
		  <input type = "radio" name = "身份" value = "老师">老师
		 <br>
		 -->
		 <p>
		
		 


        {{ 登录表单.验证码 }}
        {{ 登录表单.errors.验证码 }}
		 <button type = "submit" class = "btn btn-primary">登录</button>
		
	</form>
</body>
</html>

Login/templates/Login/register.html
<!DOCTYPE html>
<html lang="zh-hans">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>注册</h1>
    <a href=" {% url 'Login:主页' %} ">返回</a>


    <form action="" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_username">用户名:</label> 
            <input type="text" name="username" maxlength="150" autofocus required id="id_username"> 
            <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span>
        </p>
        {% if 注册表单.errors.username %}
            {{注册表单.errors.username}}
        {% endif %}

        <p>
            <label for="id_password1">密码:</label> 
            <input type="password" name="password1" required id="id_password1">
            <span class="helptext">
                <ul>
                    <li>你的密码不能与你的其他个人信息太相似。</li>
                    <li>你的密码必须包含至少 8 个字符。</li>
                    <li>你的密码不能是大家都爱用的常见密码。</li>
                    <li>你的密码不能全部为数字。</li>
                </ul>
            </span>
        </p>
        {{ 注册表单.errors.password1 }}

        <p>
            <label for="id_password2">密码确认:</label> 
            <input type="password" name="password2" required id="id_password2">
            <span class="helptext">为了校验，请输入与上面相同的密码。</span>
        </p>
        {{ 注册表单.errors.password2 }}

        <p>
            <label for="id_email">电子邮件地址:</label> 
            <input type="email" name="email" maxlength="254" id="id_email">
        </p>
        {{ 注册表单.errors.email }}

        <p>
            <label for="id_昵称">昵称:</label> 
            <input type="text" name="昵称" maxlength="50" id="id_昵称">
        </p>

        <p>
            <label for = "identity">身份:</label>
		    <input type = "radio" name = "身份" value = "学生">学生
		    <input type = "radio" name = "身份" value = "助教">助教
		    <input type = "radio" name = "身份" value = "老师">老师
		 <br>
        </p>
        {{ 注册表单.验证码 }}
        
        {{ 注册表单.errors.验证码 }}
            <button type="submit">注册</button>
    </form>

</body>

</html>

Login/templates/Login/upload.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>文件上传</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
    <h1>文件上传</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="custom-file">
            <p><input type="file" name="tttt" id="customFile" ></p>
            <label class="custom-file-label" for="customFile">选择文件</label>
        </div>
        
        <input role="button" class="btn btn-outline-primary" type="submit" value="ok">
    </form>
    {% else %}
     请先<a href = "{% url 'Login:登录' %}">登录</a>
    {% endif %}
</body>
</html>

Login/templates/Login/user-center.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>个人中心</h1>

    <a href = "{% url 'Login:主页' %}">回到主页</a>
    <a href = "{% url 'Login:编辑个人信息' %}">编辑个人信息</a>
    <a href = "{% url 'Login:修改密码' %}">修改密码</a>
    <a href = "{% url 'Login:登出' %}">登出</a>
    <div>
        <p>
            {{ 用户.username }}
        </p>

        <p>
            {{ 用户.email }}
        </p>

        <p>
            {{ 用户.普通会员表.昵称 }}
        </p>

        <p>
            {{ 用户.普通会员表.身份 }}
        </p>
    </div>

</body>
</html>